- hosts: server1
  become: yes
  tasks:
   - name: Ensure required packages are present
     apt:
       name: "{{ item }}"
       state: present
       update_cache: true
     with_items:
       - nginx
       - gnuchess
       - mysql-client

   - name: Prepare some users
     user:
       name: "{{ item.name }}"
       password: "{{ item.password }}"
       state: present
     with_items:
       - name: admin
         password: g3wo5cwAgkkx
       - name: AzureDiamond
         password: hunter2
